info:
  name: deleteSettings
  type: http
  seq: 7

http:
  method: DELETE
  url: "{{base_url}}/api/users/me/settings"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
