spring.application.name=backend

spring.mongodb.host=home-server
spring.mongodb.port=27017
spring.mongodb.database=labs_101
spring.mongodb.username=backend
spring.mongodb.password=password

spring.datasource.url=jdbc:postgresql://localhost:5432/labs101
spring.datasource.username=user
spring.datasource.password=abc123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.rest.base-path=/api
logging.level.org.springframework.data.rest=DEBUG
logging.level.org.springframework.web=DEBUG