name: Deploy to server

on:
    push:
        branches: main

permissions:
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: self-hosted
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run docker compose
              env:
                  POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
                  POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
                  ALLOWED_EMAIL_ADDRESSES: ${{ secrets.ALLOWED_EMAIL_ADDRESSES }}
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

              run: docker compose up -d --build
