name: Deploy to server

on:
    push:
        branches: main

permissions:
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: self-hosted
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run docker compose
              env:
                  POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  ZITADEL_MASTERKEY: ${{ secrets.ZITADEL_MASTERKEY }}
                  ZITADEL_DB_PASSWORD: ${{ secrets.ZITADEL_DB_PASSWORD }}
                  ZITADEL_ADMIN_PASSWORD: ${{ secrets.ZITADEL_ADMIN_PASSWORD }}
                  AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
                  AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
                  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
                  AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
                  ZITADEL_ORG_ID: ${{ secrets.ZITADEL_ORG_ID }}

              run: docker compose up -d --build
